"""Initial migration

Revision ID: 8e358a7c877f
Revises:
Create Date: 2023-03-05 06:45:36.030689

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e358a7c877f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attached_files',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('is_available', sa.Boolean(), nullable=False),
                    sa.Column('filename', sa.Text(), nullable=True),
                    sa.Column('size', sa.Integer(), nullable=True),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('owner_type', sa.Enum('EVENT', 'TASK', 'USER', 'PROCESS', name='fileownertypes'), nullable=True),
                    sa.Column('content_type', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__attached_files')),
                    sa.UniqueConstraint('filename', 'owner_id', 'owner_type', 'content_type', name='table_fields_uc')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attached_files')
    # ### end Alembic commands ###
